Changes for PowerAPI monitoring

diff --git a/.github/workflows/publish-job-success.yml b/.github/workflows/publish-job-success.yml
--- a/.github/workflows/publish-job-success.yml
+++ b/.github/workflows/publish-job-success.yml
@@ -1,37 +1,28 @@
-name: Publish Job Success Metric to CloudWatch
-
-on:
-  workflow_run:
-    workflows: "*"
-    types:
-      - completed
-    branches:
-      - master
-
-permissions:
-  id-token: write
-  contents: read
-
 jobs:
   publish-job-success-to-cloudwatch:
     if: ${{ github.event.workflow_run.event == 'schedule' }}
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::185921645874:role/djl-github-cloudwatch-ci-metrics
-          aws-region: us-west-2
-      - name: Publish Job Success Metric
-        env:
-          WORKFLOW_NAME: ${{ github.event.workflow_run.display_title }}
-          REPO_NAME: ${{ github.event.workflow_run.repository.name }}
-          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
-        run: |
-          workflow_name=$(echo "$WORKFLOW_NAME" | tr -d ' ')
-          metric_name="${REPO_NAME}-${workflow_name}-Failure"
-          failedBuild=$([ "$CONCLUSION" == "success" ]; echo $?)
-          aws cloudwatch put-metric-data --namespace GithubCI \
-            --metric-name "$metric_name" \
-            --value $failedBuild \
-            --unit Count
+    - continue-on-error: true
+      name: Configure AWS Credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-region: us-west-2
+        role-to-assume: arn:aws:iam::185921645874:role/djl-github-cloudwatch-ci-metrics
+    - continue-on-error: true
+      env:
+        CONCLUSION: ${{ github.event.workflow_run.conclusion }}
+        REPO_NAME: ${{ github.event.workflow_run.repository.name }}
+        WORKFLOW_NAME: ${{ github.event.workflow_run.display_title }}
+      name: Publish Job Success Metric
+      run: "workflow_name=$(echo \"$WORKFLOW_NAME\" | tr -d ' ')\nmetric_name=\"${REPO_NAME}-${workflow_name}-Failure\"\
+        \nfailedBuild=$([ \"$CONCLUSION\" == \"success\" ]; echo $?)\naws cloudwatch\
+        \ put-metric-data --namespace GithubCI \\\n  --metric-name \"$metric_name\"\
+        \ \\\n  --value $failedBuild \\\n  --unit Count\n"
+name: Publish Job Success Metric to CloudWatch
+on:
+  repository_dispatch:
+    types: trigger-ga___publish-job-success.yml
+permissions:
+  contents: read
+  id-token: write
